### PR TITLE
[hasec-charter] clarify Other Deliverables section

### PR DESCRIPTION
**Pull request by wayneca**
Suggested change for part of Issue #9

### CODE REVIEW

**Comment by rigow** [comment]
Doesn't harm, but just expands the meaning of the succinct statement in the charter. I'm not against. So merging if Virginie agrees

**Comment by vgalindo** [comment]
@rigow @wcarr this sounds a bit extra care for me, as it is induced by the W3C process and garanteed by the chairs that no work out of the scope will be initiated and that non-Recommandation do not induce IP binding. I would prefer to have a wording like : 
"As described above, these must be within the <a href="#scope"></a>Working Group Scope</a>.  This could include use cases or best practices for using the APIs being developed or to explore possible future work in developing future versions of this Charter."

**Comment by wayneca** [comment]
Comment in #9 that this is trying to address

> 3.3 made me nervous somehow - would it be possible to state an example of what these deliverables could be?

This is what that is referring to:

> The group may also develop other deliverables that are not Recommendations. These are not limited by the Restricted Scope. 

+1 for @vgalindo proposed wording

**Comment by wayneca** [comment]
I changed the wording in this pull request to match @vgalindo's wording.  Did I get it right?

**Comment by vgalindo** [comment]
@wcarr sounds good to me. 
@rigow can we commit and close the issue ?

**Pull request merged**
